trigger:
  batch: true
  branches:
    include:
      - staging
        
pr:
  -

pool:
  vmImage: 'vs2017-win2016'

variables:
  ASPNETCORE_ENVIRONMENT: $(CSM.ASPNETCORE_ENVIRONMENT)

steps:
  - task: PowerShell@2
    displayName: 'Env to appsettings.override.json for Web'
    inputs:
      targetType: filePath
      filePath: './deploy/env-to-json.ps1'
      arguments: '-outputPath ''./src/Web/appsettings.override.json'' -prefix ''APP_'''
    env:
      APP_Settings__ConnectionString: $(CSM.APP.Settings.ConnectionString)
      APP_Settings__FirebaseCloudMessaging__MessagingSenderId: $(CSM.APP.Settings.FirebaseCloudMessaging.MessagingSenderId)
      APP_Settings__FirebaseCloudMessaging__ServerKey: $(CSM.APP.Settings.FirebaseCloudMessaging.ServerKey)
      APP_PWA__Yandex__MapsJavaScriptAPIKey: $(CSM.APP.PWA.Yandex.MapsJavaScriptAPIKey)
      APP_Admin__JWT__SecretKey: $(CSM.APP.Admin.JWT.SecretKey)
      APP_Emulation__ConnectionString: $(CSM.APP.Emulation.ConnectionString)
      APP_Admin__JWT__Audience: $(CSM.APP.Admin.JWT.Audience)
      APP_Admin__JWT__Issuer: $(CSM.APP.Admin.JWT.Issuer)
      APP_Emulation__Enabled: $(CSM.APP.Emulation.Enabled)
      APP_Settings__ServerUrl: $(CSM.APP.Settings.ServerUrl)
      APP_Settings__Version: $(CSM.APP.Settings.Version)

  - task: PowerShell@2
    displayName: 'Env to pwasettings.json'
    inputs:
      targetType: filePath
      filePath: './deploy/env-to-json.ps1'
      arguments: '-outputPath ''./src/Web/pwasettings.json'' -prefix ''APPPWA_'''
    env:
      APPPWA_FirebaseCloudMessaging__MessagingSenderId: $(CSM_APP_Settings.FirebaseCloudMessaging.MessagingSenderId)
      APPPWA_Application__Version: $(CSM.APP.Application.Version)
      APPPWA_Application__Environment: $(CSM.ASPNETCORE_ENVIRONMENT)

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore

  - task: petersendev.dotnet-global-tool-installer.DotnetGlobalToolInstaller.DotnetGlobalToolInstaller@0
    displayName: 'Install dotnet PowerShell Tool'
    inputs:
      name: powershell
      versionSpec: x
      checkLatest: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: |
        ./src/Web/Web.csproj
        ./src/Web.IntegrationTests/Web.IntegrationTests.csproj
        ./src/Web.UnitTests/Web.UnitTests.csproj
      arguments: '--configuration $(CSM.Build.Configuration)'
      
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      arguments: '--configuration $(CSM.Build.Configuration) --output $(build.artifactstagingdirectory) -r $(CSM.Publish.Runtime)'
      zipAfterPublish: false
      
  - task: PowerShell@2
    displayName: 'Transoform web.config'
    inputs:
      targetType: filePath
      filePath: './deploy/basic/webconfig-transform.ps1'
      arguments: '-path $(build.artifactstagingdirectory)/Web/web.config'

  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/Web'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/Web.zip'
      
  - task: DeleteFiles@1
    displayName: Delete
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/Web'
      Contents: '**/*'
      RemoveSourceFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      ArtifactName: '$(CSM.Publish.ArtifactName)'