trigger:
  batch: true
  branches:
    include:
      - staging
  paths:
    exclude:
      - .run/*
      - deploy/docker/*
      - arduino/*
      - README.md
        
pr:
  -

pool:
  vmImage: 'vs2017-win2016'

variables:
  ASPNETCORE_ENVIRONMENT: $(CSM.ASPNETCORE_ENVIRONMENT)

steps:
  - task: PowerShell@2
    displayName: 'Env to appsettings.override.json Web Integration Tests'

    inputs:
      targetType: filePath
      filePath: './deploy/env-to-json.ps1'
      arguments: '-outputPath ''./src/Web.IntegrationTests/appsettings.override.json'' -prefix ''APPTESTS_'''
    env:
      APPTESTS_Settings__ConnectionString: Data Source=(localdb)\mssqllocaldb;Initial Catalog=CSM.Tests;Integrated Security=True;
      
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore

  - task: petersendev.dotnet-global-tool-installer.DotnetGlobalToolInstaller.DotnetGlobalToolInstaller@0
    displayName: 'Install dotnet PowerShell Tool'
    inputs:
      name: powershell
      versionSpec: 7.0.3
      checkLatest: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: |
        ./src/Web/Web.csproj
        ./src/Web.IntegrationTests/Web.IntegrationTests.csproj
        ./src/Web.UnitTests/Web.UnitTests.csproj
      arguments: '--configuration $(CSM.Build.Configuration)'
      
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      arguments: '--configuration $(CSM.Build.Configuration) --output $(build.artifactstagingdirectory) -r $(CSM.Publish.Runtime)'
      zipAfterPublish: false
      
  - task: PowerShell@2
    displayName: 'Transoform web.config'
    inputs:
      targetType: filePath
      filePath: './deploy/basic/webconfig-transform.ps1'
      arguments: '-path $(build.artifactstagingdirectory)/Web/web.config'

  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/Web'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/Web.zip'
      
  - task: DeleteFiles@1
    displayName: Delete
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)/Web'
      Contents: '**/*'
      RemoveSourceFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      ArtifactName: '$(CSM.Publish.ArtifactName)'