trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - .run/*
      - deploy/docker/*
      - arduino/*
      - README.md
        
pr:
  -

pool:
  vmImage: 'vs2017-win2016'

variables:
  ASPNETCORE_ENVIRONMENT: $(CSM.ASPNETCORE_ENVIRONMENT)

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore

  - task: petersendev.dotnet-global-tool-installer.DotnetGlobalToolInstaller.DotnetGlobalToolInstaller@0
    displayName: 'Install dotnet PowerShell Tool'
    inputs:
      name: powershell
      versionSpec: 7.0.3
      checkLatest: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: |
        ./src/Web/Web.csproj
        ./src/Web.IntegrationTests/Web.IntegrationTests.csproj
        ./src/Web.UnitTests/Web.UnitTests.csproj
      arguments: '--configuration $(CSM.Build.Configuration)'

  - task: DotNetCoreCLI@2
    displayName: 'Unit Tests'
    inputs:
      command: test
      arguments: './src/Web.UnitTests/Web.UnitTests.csproj --configuration $(CSM.Build.Configuration)'

  - script: |
      sqllocaldb start mssqllocaldb
    displayName: 'Start Local Db'

  - task: DotNetCoreCLI@2
    displayName: 'Smoke Tests'
    inputs:
      command: custom
      custom: 'test '
      arguments: './src/Web.IntegrationTests/Web.IntegrationTests.csproj -p:ParallelizeTestCollections=false -p:MaxParallelThreads=1 --logger trx --configuration $(CSM.Build.Configuration)  --filter Category=Smoke --results-directory $(Agent.TempDirectory)/smoke --no-build'
  
  - task: DotNetCoreCLI@2
    displayName: 'Integration Tests'
    inputs:
      command: custom
      custom: test
      arguments: './src/Web.IntegrationTests/Web.IntegrationTests.csproj -p:ParallelizeTestCollections=false -p:MaxParallelThreads=1 --logger trx --configuration $(CSM.Build.Configuration) --filter Category!=Smoke --results-directory $(Agent.TempDirectory)/default --no-build'
