services:
  webapplication:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password666"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"