version: '3.4'

services:

  web-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  web:
    image: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - web-sql-server