version: '3.4'

services:
  
  web-sql-server:
    environment:
      - SA_PASSWORD=${SQLSERVER__SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - APP_Settings__Version=${APP_Settings__Version}
      - APP_Settings__ConnectionString=${APP_Settings__ConnectionString}
      - APP_FirebaseCloudMessaging__ServerKey=${APP_FirebaseCloudMessaging__ServerKey}
      - APP_FirebaseCloudMessaging__MessagingSenderId=${APP_FirebaseCloudMessaging__MessagingSenderId}
      - APP_Settings__Version=${APP_Settings__Version}
      - APP_Settings__ServerUrl=${APP_Settings__ServerUrl}
      - APP_Emulation__ConnectionString=${APP_Emulation__ConnectionString}
      - APP_Emulation__Enabled=${APP_Emulation__Enabled}
      - APP_Admin__JWT__SecretKey=${APP_Admin__JWT__SecretKey}
      - APP_Admin__JWT__Issuer=${APP_Admin__JWT__Issuer}
      - APP_Admin__JWT__Audience=${APP_Admin__JWT__Audience}
      - APPPWA_Yandex__MapsJavaScriptAPIKey=${APPPWA_Yandex__MapsJavaScriptAPIKey}
    build:
      dockerfile: ./deploy/docker/Web.Dockerfile
      args:
        - APPPWA_FirebaseCloudMessaging__MessagingSenderId=${APP_FirebaseCloudMessaging__MessagingSenderId}
        - APPPWA_Application__Version=${APP_Settings__Version}
        - APPPWA_Application__Environment=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5080:80"
      - "5433:433"
