version: '3.4'

services:
  
  web-sql-server:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"

  web:
    env_file:
      - ./docker-compose.dev.override.env
    build:
      dockerfile: ./deploy/docker/Web.Dockerfile
      args:
        - APPPWA_FirebaseCloudMessaging__MessagingSenderId=${APP_FirebaseCloudMessaging__MessagingSenderId}
        - APPPWA_Application__Version=${APP_Settings__Version}
        - APPPWA_Application__Environment=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5080:80"
      - "5433:433"
