version: '3.4'

services:
  
  web-sql-server:
    environment:
      - SA_PASSWORD=${SQLSERVER__SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "6433:1433"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - APP_Settings__Version=${CSM_APP_SETTINGS__VERSION}
      - APP_Settings__ConnectionString=${CSM_APP_SETTINGS__CONNECTIONSTRING}
      - APP_Settings__FirebaseCloudMessaging__ServerKey=${CSM_APP_SETTINGS__FIREBASECLOUDMESSAGING__SERVERKEY}
      - APP_Settings__FirebaseCloudMessaging__MessagingSenderId=${CSM_APP_SETTINGS__FIREBASECLOUDMESSAGING__MESSAGINGSENDERID}
      - APP_Settings__ServerUrl=${CSM_APP_SETTINGS__SERVERURL}
      - APP_Emulation__ConnectionString=${CSM_APP_EMULATION__CONNECTIONSTRING}
      - APP_Emulation__Enabled=${CSM_APP_EMULATION__ENABLED}
      - APP_Admin__JWT__SecretKey=${CSM_APP_ADMIN__JWT__SECRETKEY}
      - APP_Admin__JWT__Issuer=${CSM_APP_ADMIN__JWT__ISSUER}
      - APP_Admin__JWT__Audience=${CSM_APP_ADMIN__JWT__AUDIENCE}
      - APP_PWA_Yandex__MapsJavaScriptAPIKey=${CSM_APP_PWA_YANDEX__MAPSJAVASCRIPTAPIKEY}
    build:
      dockerfile: ./deploy/docker/Web.Dockerfile
      args:
        - APPPWA_FirebaseCloudMessaging__MessagingSenderId=${CSM_APP_SETTINGS__FIREBASECLOUDMESSAGING__MESSAGINGSENDERID}
        - APPPWA_Application__Version=${CSM_APP_SETTINGS__VERSION}
        - APPPWA_Application__Environment=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5080:80"
      - "5433:433"
