pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
    SQLSERVER__SA_PASSWORD: Not Important
    ASPNETCORE_ENVIRONMENT: Not Important
    CSM_APP_SETTINGS__VERSION: Not Important
    CSM_APP_SETTINGS__CONNECTIONSTRING: Not Important
    CSM_APP_SETTINGS__FIREBASECLOUDMESSAGING__SERVERKEY: Not Important
    CSM_APP_SETTINGS__FIREBASECLOUDMESSAGING__MESSAGINGSENDERID: Not Important
    CSM_APP_SETTINGS__SERVERURL: Not Important
    CSM_APP_EMULATION__CONNECTIONSTRING: Not Important
    CSM_APP_EMULATION__ENABLED: Not Important
    CSM_APP_ADMIN__JWT__SECRETKEY: Not Important
    CSM_APP_ADMIN__JWT__ISSUER: Not Important
    CSM_APP_ADMIN__JWT__AUDIENCE: Not Important
    CSM_APP_PWA_YANDEX__MAPSJAVASCRIPTAPIKEY: Not Important
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  displayName: Build
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: './deploy/docker/docker-compose.yml'
    additionalDockerComposeFiles: 'docker-compose.override.yml'
    action: 'Build services'

- task: DockerCompose@0
  displayName: Unit Tests
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: './deploy/docker/docker-compose.tests.yml'
    additionalDockerComposeFiles: 'docker-compose.tests.override.yml'
    action: 'Run a specific service'
    serviceName: 'web-unit-tests'
- task: DockerCompose@0
  displayName: Smoke Tests
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: './deploy/docker/docker-compose.tests.yml'
    additionalDockerComposeFiles: 'docker-compose.tests.override.yml'
    action: 'Run a specific service'
    serviceName: 'web-smoke-tests'