pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
  - name: ASPNETCORE_ENVIRONMENT
    value: ${{ variables.ASPNETCORE_ENVIRONMENT }}


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo APP_Settings__Version = $(APP_Settings__Version)
- script: echo APP_Settings__Version = $APP_Settings__Version
- script: echo ASPNETCORE_ENVIRONMENT = $(ASPNETCORE_ENVIRONMENT)
- script: echo ASPNETCORE_ENVIRONMENT = $ASPNETCORE_ENVIRONMENT
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: './deploy/docker/docker-compose.yml'
#    dockerComposeFileArgs: |
#      MyNats_credentials__user=$(MyNats_credentials__user)
#      MyNats_credentials__pass=$(MyNats_credentials__pass)
    additionalDockerComposeFiles: 'docker-compose.override.yml'
    action: 'Build services'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: './deploy/docker/docker-compose.tests.yml'
    additionalDockerComposeFiles: 'docker-compose.tests.override.yml'
    action: 'Run a specific service'
    serviceName: 'web-unit-tests'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: './deploy/docker/docker-compose.tests.yml'
    additionalDockerComposeFiles: 'docker-compose.tests.override.yml'
    action: 'Run a specific service'
    serviceName: 'web-integration-tests'